### ISSUE TITLE
Cannot copy larger files (when transfer takes more than 20 seconds)

### ISSUE THREAD

**Issue by moneytoo** [alexbakker/webdav-provider#7]
I'm unable to copy/download larger files with the stock Files app. Transfer stops after 20 seconds with following in the log:

```
E/ActivityManager: ANR in me.alexbakker.webdav
    PID: 31212
    Reason: ContentProvider not responding
```

(Possibly intentional kill by Files/DocumentsUI after [20 seconds of blocking](https://android.googlesource.com/platform/frameworks/base/+/7aa7601%5E!/)? It actually always stops/fails after 20 seconds.)

Copying larger files (including transfers over 20 seconds long) works in [samba-documents-provider implementation](https://github.com/google/samba-documents-provider/blob/d211ab6e01acdde6d9c604d71da1964f2708f5cb/app/src/main/java/com/google/android/sambadocumentsprovider/provider/SambaDocumentsProvider.java#L594-L619).

Also: https://stackoverflow.com/questions/20201412/android-documentsprovider-opendocument-is-called-on-the-main-thread

(Same issue with other documents provider - https://github.com/RikyIsola/FileManagerUtils/issues/7)

**Comment by alexbakker** [comment]
I suspect it's getting stuck on ``openDocument``. It first downloads the entire file from WebDAV into the cache directory and only after that returns a ``ParcelFileDescriptor``. This is a bit of a naive implementation that should be improved.

**Comment by alexbakker** [comment]
We'll have to look into this: https://developer.android.com/reference/android/os/storage/StorageManager#openProxyFileDescriptor(int,%20android.os.ProxyFileDescriptorCallback,%20android.os.Handler). Using that API will raise ``minSdkVersion`` to 26 though

**Comment by alexbakker** [comment]
This should be fixed. Files are now properly streamed instead of cached in their entirety first. I tested this by playing back Big Buck Bunny in VLC and scrubbing through the video.

Let me know whether this works for you.

**Comment by moneytoo** [comment]
Trying to copy (or play) 2 GB video file:

```
2021-08-09 17:57:41.638 27910-27910/me.alexbakker.webdav.debug I/er.webdav.debu: Late-enabling -Xcheck:jni
2021-08-09 17:57:41.651 27910-27910/me.alexbakker.webdav.debug E/er.webdav.debu: Unknown bits set in runtime_flags: 0x8000
2021-08-09 17:57:41.680 27910-27910/me.alexbakker.webdav.debug I/Perf: Connecting to perf service.
2021-08-09 17:57:41.683 27910-27910/me.alexbakker.webdav.debug I/er.webdav.debu: [GL_OOM] ClampGrowthLimit 268435456
2021-08-09 17:57:41.685 27910-27910/me.alexbakker.webdav.debug D/WebDavProvider: onCreate()
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
2021-08-09 17:57:41.690 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
2021-08-09 17:57:41.691 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
2021-08-09 17:57:41.692 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-08-09 17:57:41.692 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
2021-08-09 17:57:41.729 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
2021-08-09 17:57:41.729 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
2021-08-09 17:57:41.729 27910-27910/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-08-09 17:57:41.745 27910-27910/me.alexbakker.webdav.debug I/EngineFactory: Provider GmsCore_OpenSSL not available
2021-08-09 17:57:41.762 27910-27910/me.alexbakker.webdav.debug V/Font: Change font:1
2021-08-09 17:57:41.762 27910-27910/me.alexbakker.webdav.debug V/Font: Default family:android.graphics.Typeface@98fe0b7d
2021-08-09 17:57:41.766 27910-27951/me.alexbakker.webdav.debug E/Perf: Fail to get file list me.alexbakker.webdav.debug
2021-08-09 17:57:41.766 27910-27951/me.alexbakker.webdav.debug E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-08-09 17:57:41.766 27910-27951/me.alexbakker.webdav.debug E/Perf: Fail to get file list me.alexbakker.webdav.debug
2021-08-09 17:57:41.766 27910-27951/me.alexbakker.webdav.debug E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-08-09 17:57:41.766 27910-27951/me.alexbakker.webdav.debug E/Perf: Fail to get file list oat
2021-08-09 17:57:41.766 27910-27951/me.alexbakker.webdav.debug E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-08-09 17:57:41.767 27910-27943/me.alexbakker.webdav.debug D/WebDavProvider: queryDocument(), documentId=/8e8d3723-c2df-428f-8693-07b4d776e609/webdav/
2021-08-09 17:57:41.776 27910-27948/me.alexbakker.webdav.debug W/er.webdav.debu: Accessing hidden method Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V (greylist, reflection, allowed)
2021-08-09 17:57:41.786 27910-27948/me.alexbakker.webdav.debug D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2021-08-09 17:57:41.796 27910-27952/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: --> PROPFIND https://my.example.com/webdav/
2021-08-09 17:57:41.825 27910-27933/me.alexbakker.webdav.debug D/WebDavProvider: queryChildDocuments(), parentDocumentId=/8e8d3723-c2df-428f-8693-07b4d776e609/webdav/, sortOrder=_display_name ASC
2021-08-09 17:57:41.827 27910-27956/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: --> PROPFIND https://my.example.com/webdav/
2021-08-09 17:57:41.920 27910-27956/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: <-- 207 https://my.example.com/webdav/ (92ms, 5476-byte body)
2021-08-09 17:57:41.922 27910-27952/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: <-- 207 https://my.example.com/webdav/ (125ms, 5476-byte body)
2021-08-09 17:57:42.056 27910-27933/me.alexbakker.webdav.debug D/WebDavProvider: queryChildDocuments(), parentDocumentId=/8e8d3723-c2df-428f-8693-07b4d776e609/webdav/, sortOrder=_display_name ASC
2021-08-09 17:57:42.061 27910-27952/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: --> PROPFIND https://my.example.com/webdav/
2021-08-09 17:57:42.074 27910-27952/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: <-- 207 https://my.example.com/webdav/ (12ms, 5476-byte body)
2021-08-09 17:57:54.759 27910-27933/me.alexbakker.webdav.debug D/WebDavProvider: queryChildDocuments(), parentDocumentId=/8e8d3723-c2df-428f-8693-07b4d776e609/webdav/, sortOrder=_display_name ASC
2021-08-09 17:57:54.762 27910-27952/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: --> PROPFIND https://my.example.com/webdav/
2021-08-09 17:57:54.775 27910-27952/me.alexbakker.webdav.debug I/okhttp.OkHttpClient: <-- 207 https://my.example.com/webdav/ (12ms, 5476-byte body)
2021-08-09 17:57:54.821 27910-27943/me.alexbakker.webdav.debug D/WebDavProvider: queryDocument(), documentId=/8e8d3723-c2df-428f-8693-07b4d776e609/webdav/video.mkv
2021-08-09 17:57:54.912 27910-27933/me.alexbakker.webdav.debug D/WebDavProvider: openDocument(), documentId=/8e8d3723-c2df-428f-8693-07b4d776e609/webdav/video.mkv, mode=r
2021-08-09 17:57:54.913 27910-27933/me.alexbakker.webdav.debug E/ContentProviderNative: onTransact error from {P:27977;U:10282}
2021-08-09 17:57:54.913 27910-27933/me.alexbakker.webdav.debug E/DatabaseUtils: Writing exception to parcel
    java.lang.NullPointerException
        at me.alexbakker.webdav.provider.WebDavProvider$WebDavFileReadProxyCallback.<init>(WebDavProvider.kt:325)
        at me.alexbakker.webdav.provider.WebDavProvider.openDocument(WebDavProvider.kt:149)
        at android.provider.DocumentsProvider.openFile(DocumentsProvider.java:1319)
        at android.content.ContentProvider$Transport.openFile(ContentProvider.java:482)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:243)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)
```

**Comment by alexbakker** [comment]
@moneytoo Which WebDAV server are you using?

**Comment by moneytoo** [comment]
I use Apache as WebDAV server, reverse proxied using nginx.

Apache conf:
```
DocumentRoot /srv/data
Alias /webdav /srv/data
<Directory /srv/data>
        Order allow,deny
        Allow from all
        # New directive needed in Apache 2.4.3:
        Require all granted

        Options Indexes
        DAV On
</Directory>
```

nginx conf:
```
    set $destination $http_destination;

    if ($destination ~* ^https(.+)$) {
         set $destination http$1;
    }

    proxy_set_header Destination $destination;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;

    location /webdav {
        proxy_pass http://127.0.0.1:8080;
    }
```

**Comment by alexbakker** [comment]
Thanks, I was able to reproduce by first copying a file to WebDAV through the Android file manager, and then immediately trying to open it afterwards. I pushed some changes, replicated your setup and am no longer able to reproduce the issue. Could you retry? If you still see issues, could you share a precise list of reproduction steps?
